# Generated by Django 4.2.7 on 2024-05-12 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
