# Generated by Django 4.2.7 on 2024-05-13 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile_profile_picture_alter_userprofile_bio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
