# Generated by Django 5.0.6 on 2024-05-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0003_attendee_check_in_time_attendee_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eventapp.event"
            ),
        ),
    ]
